const drivers=[['VER','1','Max Verstappen','#3671c6','RB'],['NOR','4','Lando Norris','#ff8000','MC'],['LEC','16','Charles Leclerc','#e8002d','FE'],['PIA','81','Oscar Piastri','#ff8000','MC'],['RUS','63','George Russell','#27f4d2','ME'],['HAM','44','Lewis Hamilton','#e8002d','FE']];
let selected=['VER'],loaded=[{code:'VER',lap:12,time:86.522}],openStint={VER:0};const $=s=>document.querySelector(s);const time=t=>'1:'+t.toFixed(3).padStart(6,'0');
function renderDrivers(){const target=$('#driverPills');target.innerHTML=drivers.map(d=>`<button class="pill ${selected.includes(d[0])?'selected':''}" style="--team:${d[3]}" data-code="${d[0]}"><i class="team-logo">${d[4]}</i>#${d[1]} · ${d[0]}</button>`).join('');target.querySelectorAll('button').forEach(b=>b.onclick=()=>{const c=b.dataset.code;if(selected.includes(c)){if(selected.length>1)selected=selected.filter(x=>x!==c)}else selected.push(c);renderDrivers();renderStints()})}
function renderStints(){const root=$('#stintPanels');root.innerHTML=selected.map(code=>{const d=drivers.find(x=>x[0]===code),active=openStint[code]||0,stints=[['Stint 1','Soft',7],['Stint 2','Medium',9],['Stint 3','Hard',5]],start=[1,8,17][active];const laps=Array.from({length:stints[active][2]},(_,i)=>{const lap=start+i,t=86.522+(code.charCodeAt(0)%7)*.067+i*.183;return `<button class="lap" style="--team:${d[3]}" data-code="${code}" data-lap="${lap}" data-time="${t}">LAP ${lap} · ${time(t)}s</button>`}).join('');return `<article class="driver-panel"><h3>${code} · ${d[2]}</h3><div class="stints">${stints.map((s,i)=>`<button class="stint ${i===active?'selected':''}" style="--team:${d[3]}" data-code="${code}" data-stint="${i}">${s[0]}<small>${s[1]} · ${s[2]} laps</small></button>`).join('')}</div><div class="lap-pills">${laps}</div></article>`}).join('');root.querySelectorAll('.stint').forEach(b=>b.onclick=()=>{openStint[b.dataset.code]=+b.dataset.stint;renderStints()});root.querySelectorAll('.lap').forEach(b=>b.onclick=()=>{if(!loaded.some(x=>x.code===b.dataset.code&&x.lap===+b.dataset.lap))loaded.push({code:b.dataset.code,lap:+b.dataset.lap,time:+b.dataset.time});renderAll()})}
function renderLoaded(){const ref=loaded[0],root=$('#loadedLaps');root.innerHTML=selected.map(code=>{const list=loaded.map((x,index)=>({...x,index})).filter(x=>x.code===code);return list.length?`<div class="loaded-line"><span>${code}</span>${list.map(x=>`<button class="pill ${x.index===0?'reference':''}" data-index="${x.index}">L${x.lap} · ${time(x.time)}<i class="remove" data-remove="${x.index}">×</i></button>`).join('')}</div>`:''}).join('');root.querySelectorAll('.pill').forEach(p=>p.onclick=e=>{const i=+p.dataset.index;if(e.target.dataset.remove!==undefined)loaded.splice(+e.target.dataset.remove,1);else loaded.unshift(loaded.splice(i,1)[0]);renderAll()});$('#referenceLap').textContent=ref?`${ref.code} · L${ref.lap} · ${time(ref.time)}`:'—';$('#loadedCount').textContent=String(loaded.length).padStart(2,'0');$('#finalDeltas').innerHTML=loaded.map((x,i)=>i?`${x.code} L${x.lap} · ${(x.time-ref.time>=0?'+':'')+(x.time-ref.time).toFixed(3)}s`:`${x.code} L${x.lap} · REFERENCE`).join('<br>')}
function renderSectors(){const root=$('#sectorRows');root.innerHTML=loaded.map((x,i)=>`<div class="sector-row sector-data"><span>${x.code} · L${x.lap}</span><span>26.${203+i*31}</span><span>31.${128+i*27}</span><span>${(x.time-57.331-i*.058).toFixed(3)}</span></div>`).join('')}
const defs=[['Speed trace','KM/H',false],['Timing delta','SECONDS VS REFERENCE',false],['Throttle application','%',true],['Brake pressure','BAR',true],['Engine speed','RPM',true],['Gear','1–8',true],['DRS / straight-line mode','ACTIVE',true]];
function renderCharts(){const root=$('#charts');root.innerHTML=defs.map(([name,unit,compact],i)=>`<section class="chart ${compact?'compact':''}"><h2>${name}<small>${unit}</small></h2>${i===0?'<div class="sector-markers"><span>SECTOR 1</span><span>SECTOR 2</span><span>SECTOR 3</span></div><div class="tooltip" id="tooltip"></div>':''}<canvas data-chart="${name}" aria-label="${name}"></canvas></section>`).join('');const speed=root.querySelector('[data-chart="Speed trace"]');speed.onmousemove=showTooltip;speed.onmouseleave=()=>$('#tooltip').style.display='none'}
function value(i,n,name){if(name==='Speed trace')return 230+72*Math.sin(i*.12+n*.2)+32*Math.sin(i*.31);if(name==='Timing delta')return n*.06+.08*Math.sin(i*.14+n*.2);if(name==='Throttle application')return Math.max(0,80+36*Math.sin(i*.21+n*.2)-44*Math.max(0,Math.sin(i*.17)));if(name==='Brake pressure')return Math.max(0,110*Math.max(0,Math.sin(i*.17+.5))**2);if(name==='Engine speed')return 8500+2900*Math.sin(i*.12+n*.2);if(name==='Gear')return Math.round(5+2.5*Math.sin(i*.12+n*.2));return (i>12&&i<23)||(i>46&&i<57)?1:0}
function range(name){return name==='Speed trace'?[0,350]:name==='Timing delta'?[-.3,.5]:name==='Brake pressure'?[0,120]:name==='Engine speed'?[5000,13000]:name==='Gear'?[0,9]:name.includes('DRS')?[0,1.2]:[0,100]}
function draw(name){const canvas=document.querySelector(`[data-chart="${name}"]`),rect=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=rect.width*d;canvas.height=rect.height*d;const x=canvas.getContext('2d'),[lo,hi]=range(name),L=43,R=5,T=7,B=10;x.scale(d,d);x.clearRect(0,0,rect.width,rect.height);x.strokeStyle='#d7d6d0';for(let k=0;k<3;k++){const y=T+(rect.height-T-B)*k/2;x.beginPath();x.moveTo(L,y);x.lineTo(rect.width-R,y);x.stroke()}loaded.forEach((lap,n)=>{x.strokeStyle=drivers.find(d=>d[0]===lap.code)[3];x.lineWidth=2;x.beginPath();for(let i=0;i<100;i++){const px=L+i*(rect.width-L-R)/99,py=T+(hi-value(i,n,name))/(hi-lo)*(rect.height-T-B);i?x.lineTo(px,py):x.moveTo(px,py)}x.stroke()})}
function drawAll(){defs.forEach(d=>draw(d[0]))}function showTooltip(e){if(!loaded.length)return;const r=e.target.getBoundingClientRect(),p=Math.max(0,Math.min(1,(e.clientX-r.left-43)/(r.width-48))),i=Math.round(p*99),tip=$('#tooltip');tip.style.display='block';tip.style.left=Math.max(43,e.clientX-r.left+10)+'px';tip.style.top=(e.clientY-r.top-23)+'px';tip.innerHTML=`<b>${(p*5.891).toFixed(3)} KM</b><br>${loaded.map((l,n)=>`${l.code} ${Math.round(value(i,n,'Speed trace'))} km/h`).join('<br>')}`}
function renderAll(){renderLoaded();renderSectors();drawAll()}$('#loadSession').onclick=()=>{selected=['VER'];loaded=[{code:'VER',lap:12,time:86.522}];openStint={VER:0};renderDrivers();renderStints();renderAll()};window.onresize=drawAll;renderDrivers();renderStints();renderCharts();renderAll();
